<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5006aa40-b755-421a-8dcf-9b017e2f37e1</testSuiteGuid>
   <testCaseLink>
      <guid>6d9b505f-e01e-40bb-a47c-b7a7608ad53b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/aa/New Test Case</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>225d99e9-f5b2-4f67-bb32-6bcc4c651d0c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Folder/asa</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>225d99e9-f5b2-4f67-bb32-6bcc4c651d0c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>a</value>
         <variableId>3fbf5c5e-d82e-44f6-a13b-6ecadeccebff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4298a4d-2a3a-4543-a9d7-554adf4303f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae01868e-941a-4c7d-8fee-6288466dedda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cba88db8-e567-4c8b-a363-53ba6d6eaa15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d383e55-f386-49ca-bc87-884f440f579d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>549c30c1-ed89-409b-84fd-086070f051e5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
