<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>thang1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b581b679-07cb-4403-b8bb-5619297b940b</testSuiteGuid>
   <testCaseLink>
      <guid>562d8275-bb1c-4d38-8bd6-bf29bffca4e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/thang/New Test Case (8)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5fcd44b9-4b31-44f2-8dca-66bdc05d5fa7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/New Folder/New Test Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78cca73b-0377-4319-b3a1-a5d1102ece91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af86012f-e54c-4fa8-9361-91f169b726b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4216036-a404-47df-8e6a-56ccef610c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d1376ab-7366-44af-ab98-97a1b6c3ae58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76e533f4-ed43-4c7c-a151-2ee7b0dad708</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41c5e54f-3bbb-47d7-b4f9-2b89eae96839</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f779f50c-fa30-44d4-b863-41c4f75368db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/thang/New Test Case (8)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0a0f4c49-e22b-4457-8d17-00f3dc7838e9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Folder/asa</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78cca73b-0377-4319-b3a1-a5d1102ece91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af86012f-e54c-4fa8-9361-91f169b726b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4216036-a404-47df-8e6a-56ccef610c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d1376ab-7366-44af-ab98-97a1b6c3ae58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76e533f4-ed43-4c7c-a151-2ee7b0dad708</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41c5e54f-3bbb-47d7-b4f9-2b89eae96839</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d825f1d-0cdc-4788-9f41-84a2f9320bbd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/thang/New Test Case (8)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>66045cb8-b7b5-415a-b453-bad4d6858251</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Folder/New Test Data (1)</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78cca73b-0377-4319-b3a1-a5d1102ece91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af86012f-e54c-4fa8-9361-91f169b726b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4216036-a404-47df-8e6a-56ccef610c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d1376ab-7366-44af-ab98-97a1b6c3ae58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76e533f4-ed43-4c7c-a151-2ee7b0dad708</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41c5e54f-3bbb-47d7-b4f9-2b89eae96839</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61c799da-34d9-4f53-a8b4-057d8ffc9e0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/thang/New Test Case (8)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bb961346-1d1f-471f-bc21-e00eb38ac8f2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Folder/New Test Data (2)</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78cca73b-0377-4319-b3a1-a5d1102ece91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af86012f-e54c-4fa8-9361-91f169b726b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4216036-a404-47df-8e6a-56ccef610c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d1376ab-7366-44af-ab98-97a1b6c3ae58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76e533f4-ed43-4c7c-a151-2ee7b0dad708</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41c5e54f-3bbb-47d7-b4f9-2b89eae96839</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>189191c5-ca31-4663-9f08-aa8945d5bd74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/thang/New Test Case (8)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>80f6e6f8-791c-4e9c-82f8-e2599ba8f72f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Folder/s</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78cca73b-0377-4319-b3a1-a5d1102ece91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af86012f-e54c-4fa8-9361-91f169b726b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4216036-a404-47df-8e6a-56ccef610c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d1376ab-7366-44af-ab98-97a1b6c3ae58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76e533f4-ed43-4c7c-a151-2ee7b0dad708</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41c5e54f-3bbb-47d7-b4f9-2b89eae96839</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
